blog/urls.py


from django.urls import path
from . import views

app_name = 'blog'


urlpatterns = [
    # path('', views.index, name="index"),
    path('', views.blog, name="blog"),
    path('create', views.blog_create, name="blog_create"),
    path('details/<int:id>/', views.blog_details, name="blog_detailpage"),
    path('update/<int:id>/', views.blog_update, name="blog_update"),
    path('delete/', views.blog_delete, name="blog_delete"),

]

cart/urls.py
from django.conf.urls import url
from . import views

app_name = 'cart'

urlpatterns = [
    url(r'^$', views.cart_detail, name='cart_detail'),
    url(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    url(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
   
    path('mainstore/', admin.site.urls),
    path('cart', include('cart.urls')),
    path('orders/', include('orders.urls')),
    path('forum/', include("blog.urls")),
    path('', include('shop.urls')),
  
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

app_name = 'shop'


urlpatterns = [
    path('aggrey', views.product_list, name ='product_list'),
    path('',views.listAll,name = 'allproductlist'),
    path('uniqpab_faqs',views.unique_faqs,name ='faq'),
    path('category',views.allCategory,name ='category'),
    path('allrelated/<int:p_id>/',views.allRelated,name ='allrelated'),
    url(r'^(?P<category_slug>[-\w]+)/$', views.product_list, name='product_list_by_category'),
    url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.product_detail, name='product_detail'),
    
]

shop/models.py
from django.db import models
from django.urls import reverse


class Category(models.Model):
    name = models.CharField(max_length=150, db_index=True)
    slug = models.SlugField(max_length=150, unique=True ,db_index=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    image = models.ImageField(upload_to='category_img/%Y/%m/%d', blank=False,null=True)
   
  
    class Meta:
        ordering = ('-created_at', )
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_list_by_category', args=[self.slug])


class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products_img', on_delete=models.CASCADE)
    name = models.CharField(max_length=100, db_index=True)
    slug = models.SlugField(max_length=100, db_index=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    available = models.BooleanField(default=True)
    stock = models.PositiveIntegerField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    image = models.ImageField(upload_to='products_img/%Y/%m/%d', blank=False,null=True)
    image1 = models.ImageField(upload_to='products_img/%Y/%m/%d', blank=True,null=True)
    image2 = models.ImageField(upload_to='products_img/%Y/%m/%d', blank=True,null=True)
    image3 = models.ImageField(upload_to='products_img/%Y/%m/%d', blank=True,null=True)





    class Meta:
        ordering = ('-name', )
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_detail', args=[self.id, self.slug])

# work on this later
class Gallary(models.Model):
    image1 = models.ImageField(upload_to='gallary_img/%Y/%m/%d', blank=True,null=True)
    image2 = models.ImageField(upload_to='gallary_img/%Y/%m/%d', blank=True,null=True)
    image3 = models.ImageField(upload_to='gallary_img/%Y/%m/%d', blank=True,null=True)
    image4 = models.ImageField(upload_to='gallary_img/%Y/%m/%d', blank=True,null=True)
    image5 = models.ImageField(upload_to='gallary_img/%Y/%m/%d', blank=True,null=True)
    image6 = models.ImageField(upload_to='gallary_img/%Y/%m/%d', blank=True,null=True)


   

shop/views.py
from django.shortcuts import render, get_object_or_404
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.db.models import Q
from .models import Category, Product, Gallary
from cart.forms import CartAddProductForm


def listAll(request):    
    gallary = Gallary.objects.all()
    
    # allproduct =Product.objects.all().order_by('-created_at')
    queryset_list  = Product.objects.filter(available=True) 

    # not paginating 
    paginator = Paginator(queryset_list, 2)
    page = request.GET.get('page')
    paginator_list = paginator.get_page(page)

    query = request.GET.get('keyword')
    if query:
        queryset_list =  queryset_list.filter(Q(name__icontains=query) | 
        Q(category__name__icontains=query)|
        Q(description__icontains=query)
        )
       
   

    context ={
        'allproduct':queryset_list,
        'gallarys':gallary
          
    }

    return render(request, 'shop/product/mylist.html', context)

def allCategory(request):
    queryset_list = Category.objects.all()

    query = request.GET.get('keyword')
    if query:
        queryset_list =  queryset_list.filter(name__icontains=query)
    notfound ='nothing much your search result'


    context ={
        'categorys': queryset_list,
      
    }

    return render(request, 'shop/product/allcategory.html', context)

def allRelated(request,p_id):
    # allrelated = Product.objects.select_related('category',id = c_id)
    # allRelated = Product.objects.get(id=p_id)
    # allrelated =Product.objects.select_related('category')
    category =Category.objects.all()
    if p_id:
        category = get_object_or_404(Category, id=p_id)
        products = Product.objects.filter(category=category)

    
    context ={
        'allrelated':products,
        
    }
    return render(request, 'shop/product/allrelatedproduct.html', context)
    
def unique_faqs(request):
    context ={
        
    }
    return render(request, 'shop/product/faq.html', context)


def product_list(request, category_slug=None):
   
    category = None
    categories = Category.objects.all()
    queryset_list = Product.objects.filter(available=True)
    query = request.GET.get('keyword')
    if query:
        queryset_list = queryset_list.filter(Q(name__icontains = query)|Q(price__lte=query))

    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = Product.objects.filter(category=category)

    context = {
        'category': category,
        'categories': categories,
        'products': queryset_list,
        
    }
    return render(request, 'shop/product/list.html', context)


def product_detail(request, id, slug):
    product = get_object_or_404(Product, id=id, slug=slug, available=True)
    cart_product_form = CartAddProductForm()
    context = {
        'product': product,
        'cart_product_form': cart_product_form
    }
    return render(request, 'shop/product/detail.html', context)


def search_product(request):
    # queryset_list = Product.objects.filter(available=True)
    queryset_list = Product.objects.order_by('-created_at')

    query = request.GET.get('keyword')
    if query:
        queryset_list = queryset_list.filter(Q(name__icontains = query)|Q(price__lte=query))
    size = len(queryset_list)

    context = {
        'search_result':queryset_list,
        'resultSize': size,
    }

    return render(request, 'shop/product/search.html',context)


def mygallery (request):

    gallary = Gallary.objects.all()

    context = {
        'gallary': gallary,
    }
    return render(request,'shop/partials/carousel.html', context )

shop/templates/shop/product/allcategory.html
{% extends 'shop/base.html' %}

{% block title %}
{% if category %}uniqpab|{{ category.name }} {% else %} uniqpab|Products {% endif %}
{% endblock %}


{% block content %}


<div class="container-fluid">
  

    <h4 class="text-center "> <u>All Categories</u></h4><hr>

    <form method="GET" action="">

  <input class="mx-4 mb-5 allign-center px-3" type="text" name="keyword" id="" placeholder="search" value="{{ request.GET.keyword }}">
  <button type="submit">search</button>

<hr>

{% if categorys %}
<!-- <h5>{{ categorys|length }}</5> -->
    {% else %}
    <h4 class="text-danger"> sorry no result mach your search</h4>
{% endif %}

{% for allcategory in categorys %}

<a href="{% url 'shop:allrelated' allcategory.id %}">
  <div class="card-deck">
    <div class="card text-center">
      {% if allcategory.image %}
       <img class="float-left img-thumbnail" src="{{ allcategory.image.url }}" alt="">
      {% endif %}
     
      <div class="card-body">
        <!-- <h5 class="card-title">Title</h5> -->
        <p class="card-text text-capitalize">{{  allcategory.name }}</p>
      </div>
      <hr>
    </div>
  </div>
</a>
<br>

{% endfor %}

</div>

{% endblock  %}

shop/templates/shop/product/allrelatedproduct.html
{% extends 'shop/base.html' %}
{% load static %}
{% block title %}
{% if category %}{{ category.name }} {% else %} Products {% endif %}
{% endblock %}

{% block content %}

<div class="container">
    <div class="row">

        {% for similar_product in allrelated %}

        <div class="col-md-4">
          <div class="thumbnail">

            <a href="{{ similar_product.get_absolute_url }}">
              <img
                src="{% if similar_product.image %} {{ similar_product.image.url }} {% else %} {% static 'img/default.jpg' %} {% endif %}"
                alt="..." style="height: 130px; width: auto">
            </a>
            <div class="caption">
              <h3 class="text-center">
                <a href="{{ similar_product.get_absolute_url }}">{{ similar_product.name }}</a>
              </h3>
              <p class="text-center text-danger">GH₵ {{ similar_product.price }}</p>
            </div>
          </div>
        </div>
        {% endfor %}
    </div>

    
</div>




{% endblock %}

shop/templates/shop/product/detail.html
{% extends 'shop/base.html' %}

{% load static %}

{% block title %}
{% if category %}{{ category.name }} {% else %} Products {% endif %}
{% endblock %}

{% block content %}

<div class="container">
    <div class="row" style="margin-top: 6%">

        <div class="col-sm-8 blog-main">

            <div class="blog-post">
                <div class="row">
                    <div class="card">
                        <div class="card-body">
                            <nav aria-label="Page breadcrumb">
                                <ol class="breadcrumb">
                                    <li class="breadcrumb-item active" aria-current="page"><a href="{% url 'shop:allproductlist' %}">home</a></li>
                                    <li class="breadcrumb-item">details</li>
                                </ol>
                            </nav>
                            <div class="col-md-6 text-right">
                                <img src="{% if product.image %} {{ product.image.url }} {% else %} {% static 'img/default.jpg' %} {% endif %}"
                                    alt="..." style="height: 300px; width: auto">
                            </div>
                            <!-- Thumbnails -->

                            <div class="row mb-5 thumbs text-center">
                                {% if product.image1 %}
                                <div class="col-sm-4 col-md-4 col-lg-4">
                                    <a href="" data-lightbox="products-images">

                                        <img src="" alt="" class="img-fluid">
                                    </a>
                                </div>
                                {% endif %}
                                {% if product.image2 %}
                                <div class=" col-sm-4  col-md-4 col-lg-4">
                                    <a href="" data-lightbox="products-images">
                                        <img src="" alt="" class="img-fluid">
                                    </a>
                                </div>
                                {% endif %}
                                {% if product.image3 %}
                                <div class="col-sm-4  col-md-4 col-lg-4">
                                    <a href="" data-lightbox="products-images">
                                        <img src="" alt="" class="img-fluid">
                                    </a>
                                </div>

                                {% endif %}

                            </div>
                            <!--end of  Thumbnails -->

<!-- carousel -->

<!DOCTYPE html>
{% load static %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<link rel="stylesheet" href=" {% static 'css/carousel_style.css' %} "> 

 <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>


    <div class="container">
       
      <div id="logoCarousel" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators black">
  
          <li data-target="#logoCarousel" data-slide-to="0" class="active"></li>
          <li data-target="#logoCarousel" data-slide-to="1"></li>
          <li data-target="#logoCarousel" data-slide-to="2"></li>
        </ol>
        <div class="carousel-inner">

          <div class="item active">

            {% if  product.image2 %}
            
             <img src=" {{  product.image2.url  }} " alt="no image available" >
            {% endif %}
           
            <div class="carousel-caption">
               
                <!-- <h3 class="text-left">GH₵: {{ product.price }}</h3> -->

            </div>
          </div>

          <div class="item">


            {% if  product.image1 %}
            
             <img src=" {{  product.image1.url  }} " alt="no image available">
            {% endif %}

            <div class="carousel-caption">
             
              <!-- <h3>{{ product.price }}</h3> -->
            </div>
          </div>

          <div class="item">


            {% if  product.image3 %}
            
             <img src=" {{  product.image3.url  }}  " alt="no image available">
            {% endif %}

            <div class="carousel-caption">
             
              <!-- <h3>{{ product.price }}</h3> -->
            </div>
          </div>

          
         

        <a class="left carousel-control" href="#logoCarousel" data-slide="prev">
          <span class="glyphicon glyphicon-chevron-left"></span>
        </a>
        <a class="right carousel-control" href="#logoCarousel" data-slide="next">
          <span class="glyphicon glyphicon-chevron-right"></span>
        </a>
      </div>
    </div>
    </div>



<!-- end of carousel -->



                            <div class="col-md-6" style="padding-left: 20px">
                                <h3>{{ product.name }}</h3>
                                <h6><a href="{{ product.category.get_absolute_url }}">{{ product.category }}</a></h6>
                                <p class="text-danger">GH₵: {{ product.price }}</p>
                                <form action="{% url "cart:cart_add" product.id %}" method="post">
                                    {% csrf_token %}
                                    <hr>
                                    {{ cart_product_form }}
                                    <input type="submit" value="add to cart" class="btn btn-primary"> <br>
                                
                                </form>
                                <hr>
                                <a class="" href="tel:+233246394796">
                                    <i class="fa fa-phone" aria-hidden="true"> call to order</i><br>
                                   
                                   </a>
                                   
                                <br>
                                <p class="text-muted">{{ product.description|safe|linebreaksbr }}</p>
                                
                            </div>
                        </div>
                    </div>
                </div>


            </div><!-- /.blog-post -->

        </div><!-- /.blog-main -->
    </div><!-- /.row -->

</div><!-- /.container -->


{% endblock %}

shop/templates/shop/product/faq.html
{% extends 'shop/base.html' %}

{% block title %}
Uniqpab FAQ
{% endblock %}


{% block content %}

<div class="container">
   <div class="row">
     <div class="col">
      
      <h4> FAQ </h4>

      <div class="accordion" id="accordionExample">
          <div class="card">
            <div class="card-header" id="headingOne">
              <h2 class="mb-0">
                <button class="btn btn-block lead text-info" type="button" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                 How do we create an account with you
                </button>
              </h2>
            </div>
        
            <div id="collapseOne" class="collapse show" aria-labelledby="headingOne" data-parent="#accordionExample">
              <div class="card-body">
             
             <h4>
               currently creating an account is not inplemented thank you for asking
             </h4>
                <div>
            </div>
          </div>
      
          <div class="card">
            <div class="card-header" id="headingTwo">
              <h2 class="mb-0">
                <button class="btn btn-block  collapsed lead text-info" type="button" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                 how do we receive my product
                </button>
              </h2>
            </div>
            <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionExample">
              <div class="card-body">
              <h4>
  
                  you can receive your product either at home or you can personally walk to our office for 
                your product and our team will be willing to assist you
            
              </h4>
              </div>
            </div>
          </div>
          <div class="card">
            <div class="card-header" id="headingThree">
              <h2 class="mb-0">
                <button class="btn btn-block text-info collapsed lead text-info" type="button" data-toggle="collapse" data-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
                 How would i know if my purchase went succcesful
                </button>
              </h2>
            </div>
            <div id="collapseThree" class="collapse" aria-labelledby="headingThree" data-parent="#accordionExample">
              <div class="card-body">
              
                <h4>
                    with this there are two options <br>
                1.  upon pressing of the submit button at where you input your info
                an email will be sent automatically to the email you provided <br>
                2.  ourcustomer representative will contact you emediatly your submission enters our records (database) 
             
                </h4>
              </div>
            </div>
          </div>
      
      
          <!-- MY OWN -->
          <div class="card">
              <div class="card-header" id="headingOne">
                <h2 class="mb-0">
                  <button class="btn btn-block  lead text-info" type="button" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                    How can i reach you in case of assistance
                  </button>
                </h2>
              </div>
          
              <div id="collapseOne" class="collapse show" aria-labelledby="headingOne" data-parent="#accordionExample">
                <div class="card-body">
                <h4>
                    you can reach us by  clicking on this
                  <a href="tel:+233240699506">contact</a> <br>
                  or through  <a href="https://wa.me/+233240699506">whatsapp</a><br>
                  <h6 text-light> send us an email: uniquepab@gmail.com</h6>

      
                </h4>
      
                </div>
              </div>
            </div>
      
            <!--  -->
            <div class="card">
                <div class="card-header" id="headingOne">
                  <h2 class="mb-0"> 
                    <button class="btn btn-block  lead text-info" type="button" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                     Do you guys receive online payment or mobile money
                    </button>
                  </h2>
                </div>
            
                <div id="collapseOne" class="collapse show" aria-labelledby="headingOne" data-parent="#accordionExample">
                  <div class="card-body">
                  <h4>
                      No we don't currently we hope to introduce those in the future <br>
                    we do receive mobile  money through this MTN <i>number</i> <small> <u>0240699506</u> </small>
                 
                  </h4>
  
                  </div>
                </div>
              </div>
              <!--  -->
        </div>
      
      

     </div>
   </div>
    
</div>

  
{% endblock  %}

shop/templates/shop/product/list.html
{% extends 'shop/base.html' %}
{% load static %}
{% block title %}
{% if category %}{{ category.name }} {% else %} Products {% endif %}
{% endblock %}

{% block content %}

<div class="container-fluid">

    <form method="GET" action="">

  <input class="my-3" type="text" name="keyword" id="" placeholder="search" value="{{ request.GET.keyword }}">
  <button type="submit">search</button>


  <div class="row" style="margin-top: 6%">

    <div class="col-sm-8 blog-main">


      <div class="blog-post">
        <div class="row">


            {% for product in products %}


            <div class="col-md-4">
              <div class="thumbnail">

                <a href="{{ product.get_absolute_url }}">
                  <img
                    src="{% if product.image %} {{ product.image.url }} {% else %} {% static 'img/default.jpg' %} {% endif %}"
                    alt="..." style="height: 130px; width: auto">
                </a>
                <div class="caption">
                  <h3 class="text-center">
                    <a href="{{ product.get_absolute_url }}">{{ product.name }}</a>
                  </h3>
                  <p class="text-center text-danger">GH₵: {{ product.price }}</p>
                </div>
              </div>
            </div>
            {% endfor %}
        </div>


      </div><!-- /.blog-post -->

    </div><!-- /.blog-main -->

    <div class="col-sm-3 col-sm-offset-1 blog-sidebar">
      <div class="sidebar-module">
        <h4>Categories</h4>
        <ol class="list-unstyled">
          <li {% if not category %} class="active" {% endif %}><a href="{% url 'shop:product_list' %}">All</a></li>
          {% for c in categories %}

          <li {% if category.slug == c.slug %} class="active" {% endif %}>
            <a href="{{ c.get_absolute_url }}">{{ c.name }}</a>
          </li>
          {% endfor %}
        </ol>
      </div>
    </div><!-- /.blog-sidebar -->

  </div><!-- /.row -->

</div><!-- /.container -->
</form>
{% endblock %}

shop/templates/shop/product/mylist.html
{% extends 'shop/base.html' %}
{% load static %}
{% block title %}
{% if category %}uniqpab|home{{ category.name }} {% else %} uniqpab {% endif %}
{% endblock %}

{% block content %}


<div class="container-fluid">

    <form method="GET" action="">

  <input class="mx-4 mb-5 allign-center px-3" type="text" name="keyword" id="" placeholder="search" value="{{ request.GET.keyword }}">
  <button type="submit">search</button>


  <div class="row" style="margin-top: 6%">

    <div class="col-sm-8 blog-main">


      <div class="blog-post">
        <div class="row">


{% if allproduct %}
<!-- <h5>{{ allproduct|length }}</5> -->
    {% else %}
    <h4 class="text-danger"> sorry no result mach your search</h4>
{% endif %}

            {% for product in allproduct %}
  

            <div class="col-md-4">
              <div class="thumbnail">

                <a href="{{ product.get_absolute_url }}">
                  <img
                    src="{% if product.image %} {{ product.image.url }} {% else %} {% static 'img/default.jpg' %} {% endif %}"
                    alt="..." style="height: 130px; width: auto">
                </a>
                <div class="caption">
                  <h3 class="text-center">
                    <a href="{{ product.get_absolute_url }}">{{ product.name }}</a>
                  </h3>
                  
                  <p class="text-center text-danger">GH₵:{{ product.price }}</p>
                </div>
              </div>
            </div>
           

            {% endfor %}
           
        </div>


      </div><!-- /.blog-post -->

    </div><!-- /.blog-main -->
<!-- side bar -->
    <!-- <div class="col-sm-3 col-sm-offset-1 blog-sidebar">
      <div class="sidebar-module">
        <h4>Categories</h4>
        <ol class="list-unstyled">
          <li {% if not category %} class="active" {% endif %}><a href="{% url 'shop:product_list' %}">All</a></li>
          {% for c in categories %}

          <li {% if category.slug == c.slug %} class="active" {% endif %}>
            <a href="{{ c.get_absolute_url }}">{{ c.name }}</a>
          </li>
          {% endfor %}
        </ol>
      </div>
    </div>/.blog-sidebar -->
<!-- end of side bar -->
  </div><!-- /.row -->

</div><!-- /.container -->
</form>


{% endblock %}

shop/templates/shop/product/search.html
{% extends 'shop/base.html' %}
{% load static %}

{% block content %}

  <div class="blog-post">
              <div class="row">
                  {% for product in search_result %}

               
                      <div class="col-md-4">
                        <div class="thumbnail">

                            <a href="{{ product.get_absolute_url }}">
                                <img src="{% if product.image %} {{ product.image.url }} {% else %} {% static 'img/default.jpg' %} {% endif %}" alt="..." style="height: 130px; width: auto">
                            </a>
                            <div class="caption">
                                <h3 class="text-center">
                                    <a href="{{ product.get_absolute_url }}">{{ product.name }}</a>
                                </h3>
                                <p class="text-center text-danger">GH₵: {{ product.price }}</p>
                            </div>
                        </div>
                      </div>
                  {% endfor %}
              </div>


          </div><!-- /.blog-post -->
{% endblock content %}

  <div class="blog-post">
              <div class="row">
                  {% for product in search_result %}

               
                      <div class="col-md-4">
                        <div class="thumbnail">

                            <a href="{{ product.get_absolute_url }}">
                                <img src="{% if product.image %} {{ product.image.url }} {% else %} {% static 'img/default.jpg' %} {% endif %}" alt="..." style="height: 130px; width: auto">
                            </a>
                            <div class="caption">
                                <h3 class="text-center">
                                    <a href="{{ product.get_absolute_url }}">{{ product.name }}</a>
                                </h3>
                                <p class="text-center text-danger">GH₵: {{ product.price }}</p>
                            </div>
                        </div>
                      </div>
                  {% endfor %}
              </div>


          </div><!-- /.blog-post -->